# Generated by Django 4.1.2 on 2022-10-26 06:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('image', models.URLField()),
                ('price', models.FloatField()),
                ('release_date', models.DateField(default=datetime.date(2022, 10, 26))),
                ('lte_exists', models.BooleanField(default=True)),
                ('slug', models.SlugField()),
            ],
        ),
    ]
